Church/Church/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('menu/',include('menu.urls')),
    path("accounts/", include("accounts.urls")),
    path("store/",include("store.urls")),
    path("userpage/",include("userpage.urls")),
    path("mypage/",include("mypage.urls")),
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #後で理解

Church/menu/urls.py
from django.urls import path,include
from . import views


urlpatterns = [
    path('',views.index,name='index'),
    path('list/',include('forum.urls')),
    path('dogmatics/',include('dogmatics.urls')),
    path('back/',views.back,name="back"),
]

Church/mypage/urls.py
from django.urls import path
from . import views

app_name = "mypage"

urlpatterns = [
    #path('',views.userpage),
    path('',views.mypage, name="mypage"),
    path('preprint_delete/<int:preprint_id>/',views.preprint_delete, name="preprint_delete"),

]

Church/mypage/models.py
from django.db import models

# Create your models here.

Church/mypage/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from dogmatics.models import Preprint,FormalPaper
from forum.models import Post
from django.shortcuts import get_object_or_404, redirect

# Create your views here.
def mypage(request):

    #user_nameをユニークにする
    user = request.user
    preprints = Preprint.objects.filter(author=user)
    formal_papers = []
    for preprint in preprints:
        if FormalPaper.objects.filter(preprint=preprint):
            formal_papers.append(FormalPaper.objects.filter(preprint=preprint))
    posts = Post.objects.filter(owner=user)


    params = {
        'user' : user,
        'preprints' : preprints,
        'formal_papers'  : formal_papers,
        'posts' : posts,
    }

    
    return render(request, 'mypage/mypage.html', params)

def preprint_delete(request,preprint_id):
        
    if request.method == "POST":

        preprint = get_object_or_404(Preprint, id=preprint_id)
        preprint.delete()

        return redirect('mypage:mypage')
    
    return redirect('mypage:mypage')

Church/mypage/templates/mypage/mypage.html
{% extends "base.html" %}
{% load markdown_extras %}

{% block main %}
    <body>
        <p>{{ user.username }}</p>

        <!-- Postsの表示 -->
        {% for post in posts %}
        <p>
            {{ post.verse.chapter.book.name }} {{ post.verse.chapter.chapter_number }} : {{ post.verse.verse_number }}<br>
            {{ post.text }}<br>
        </p>
        {% endfor %}

        <!-- Preprintsの表示 -->
        {% for preprint in preprints %}
        <div class="preprint">
            <h3>{{ preprint.title }}</h3>
            <div>{{ preprint.content|markdown|safe }}</div>

            <!-- 削除ボタン -->
            <form action="{% url 'mypage:preprint_delete' preprint.id %}" method="POST" class="mt-3">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm btn-dark">delete</button>
            </form>
        </div>
        <hr>
        {% endfor %}
    </body>
{% endblock %}