Church/Church/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('menu/',include('menu.urls')),
    path("accounts/", include("accounts.urls")),
    path("store/",include("store.urls")),
    path("userpage/",include("userpage.urls")),
    path("mypage/",include("mypage.urls")),
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #後で理解

Church/forum/urls.py
from django.urls import path
from . import views
from .models import Book,Chapter,Verse

urlpatterns = [
    path('',views.list,name='list'),
    path("book",views.book,name="book"),
    path("book/forum",views.forum,name="forum"),
]

Church/menu/urls.py
from django.urls import path,include
from . import views


urlpatterns = [
    path('',views.index,name='index'),
    path('list/',include('forum.urls')),
    path('dogmatics/',include('dogmatics.urls')),
    path('back/',views.back,name="back"),
]

Church/userpage/urls.py
from django.urls import path
from . import views

app_name = "userpage"

urlpatterns = [
    #path('',views.userpage),
    path('<str:username>/',views.userpage, name="userpage"),

]

Church/forum/models.py
from django.db import models
from django.contrib.auth.models import User

class Book(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Chapter(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    chapter_number = models.IntegerField()

    def __str__(self):
        return f"{self.book.name} {self.chapter_number}"

class Verse(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    verse_number = models.IntegerField()
    text = models.TextField()
    image = models.ImageField(upload_to='img/wordcloud/',null=True)

    def __str__(self):
        return f"{self.chapter.book.name} {self.chapter.chapter_number}:{self.verse_number}"
    
class Post_test(models.Model):
    name = models.CharField(max_length=100)
    text = models.TextField()
    
    def __str__(self):
        return self.text
    
class Post(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="message_owner", null=True)
    guest_name = models.CharField(max_length=100, null=True)
    text = models.TextField()
    verse = models.ForeignKey(Verse, on_delete=models.CASCADE, related_name="post")
    created_at = models.DateTimeField(auto_now_add=True)

Church/forum/forms.py
from django import forms 

class DiscussionForm(forms.Form):
    
    text = forms.CharField(label="Content", widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4}))

class DiscussionForm_guest(forms.Form):
    guest_name = forms.ChoiceField(label="Guest name",widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 300px;'}))
    text = forms.CharField(label="Content", widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4}))


class PageForm(forms.Form):
    page_number = forms.IntegerField(label="Enter Chapter Number",required=True)

Church/forum/views.py
from django.shortcuts import render, get_object_or_404
from .models import Book,Post,Chapter,Verse
from .forms import DiscussionForm,PageForm,DiscussionForm_guest
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django_ratelimit.decorators import ratelimit

bible_order = [
        "genesis", "exodus", "leviticus", "numbers", "deuteronomy", "joshua",
        "judges", "ruth", "1samuel", "2samuel", "1kings", "2kings", "1chronicles", 
        "2chronicles", "ezra", "nehemiah", "esther", "job", "psalms", "proverbs", 
        "ecclesiastes", "songofsongs", "isaiah", "jeremiah", "lamentations", 
        "ezekiel", "daniel", "hosea", "joel", "amos", "obadiah", "jonah", 
        "micah", "nahum", "habakkuk", "zephaniah", "haggai", "zechariah", "malachi",
        "matthew", "mark", "luke", "john", "acts", "romans", "1corinthians", 
        "2corinthians", "galatians", "ephesians", "philippians", "colossians", 
        "1thessalonians", "2thessalonians", "1timothy", "2timothy", "titus", 
        "philemon", "hebrews", "james", "1peter", "2peter", "1john", "2john", 
        "3john", "jude", "revelation"
    ]

books = Book.objects.filter(name__in=bible_order)
ordered_books = sorted(books, key=lambda x: bible_order.index(x.name.lower()))

def list(request):
    
    params = {
        "books":ordered_books,
    }

    return render(request,'forum/list.html',params)

def book(request,num=1):

    book_name = request.GET.get("name")

    num = request.GET.get("page")

    if num is None:
        page = 1
    
    verses = []
    book = get_object_or_404(Book, name=book_name)
    chapters = book.chapter_set.all().order_by("chapter_number")
    for id,chapter in enumerate(chapters):
        verse_set = chapter.verse_set.all().order_by("verse_number")
        verses.append((verse_set,id+1))

    page = Paginator(verses,1)

    params = {
        "book":book_name,
        "chapters":chapters,
        "verses":page.get_page(num),
        "form":PageForm(),
        
    }

    if (request.method == 'POST'):
        num = int(request.POST["page_number"])
        params["verses"] = page.get_page(num)


    return render(request,"forum/book.html",params)

def forum(request):

    name = request.GET["name"]
    chapter_number = request.GET["chapter"]
    verse_number = request.GET["verse"]

    book = Book.objects.filter(name=name).first()
    chapter = Chapter.objects.filter(book=book, chapter_number=chapter_number).first()
    verse=Verse.objects.filter(verse_number=verse_number, chapter=chapter).first()


    post = Post.objects.filter(verse__chapter__book__name = name, verse__chapter__chapter_number=chapter_number, verse__verse_number=verse_number).order_by("-created_at")

    can_post = 1

    if request.user.is_authenticated:
        form = DiscussionForm()
            
    else:
        form = DiscussionForm_guest()
            
    params = {

        "name":book.name,
        "chapter":chapter,
        "verse":verse,
        "form":form,
        "post":post,
        "can_post" : can_post

    }

    if (request.method == 'POST'):

        was_limited = False#ratelimit(key='ip', rate='5/m', method='POST', block=False)(lambda x: True)(request)

        if not was_limited:

            params["can_post"] = 1

            if request.user.is_authenticated:

                user = request.user
                post_text = request.POST["text"]
                name=request.GET["name"]
                chapter=request.GET["chapter"]
                verse_number=request.GET["verse"]
                post_verse = Verse.objects.get(verse_number=verse_number, chapter__chapter_number=chapter, chapter__book__name=name)

                post = Post(owner=user,text=post_text,verse=post_verse)     
                post.save() 
                params["post"] = Post.objects.filter(verse__chapter__book__name = name, verse__chapter__chapter_number=chapter_number, verse__verse_number=verse_number).order_by("-created_at")



            else:
                guest_name = request.POST["guest_name"]
                post_text = request.POST["text"]
                name=request.GET["name"]
                chapter=request.GET["chapter"]
                verse_number=request.GET["verse"]
                post_verse = Verse.objects.get(verse_number=verse_number, chapter__chapter_number=chapter, chapter__book__name=name)

                post = Post(guest_name=guest_name,text=post_text,verse=post_verse)     
                post.save() 
                params["post"] = Post.objects.filter(verse__chapter__book__name = name, verse__chapter__chapter_number=chapter_number, verse__verse_number=verse_number).order_by("-created_at")

        else:
            params["can_post"] = 0

    return render(request,"forum/forum.html",params)

Church/forum/templates/forum/book.html
{% extends "base.html" %}

{% block main %}
    <body>
        <h1>{{book}}</h1>
        {% for verse_set, id in verses %}
        <p>Chapter:{{id}}</p>
        {% for verse in verse_set %}
        <a href="{% url 'forum' %}?name={{book}}&chapter={{id}}&verse={{verse.verse_number}}" class="text-dark">
            <p>{{verse.verse_number}}: {{verse.text}}</p>
        </a>
        {% endfor %}
        {% endfor %}

        <ul class="pagination">
            {% if verses.has_previous %}
            <li class="page-item">
                <a class="page-link text-dark" href="{% url 'book' %}?name={{book}}">
                    &laquo; first
                </a>
            </li>
            <li class="page-item">
                <a class="page-link text-dark" href="{% url 'book' %}?name={{book}}&page={{verses.previous_page_number}}">
                    &laquo; prev
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <span class="page-link text-muted">&laquo; first</span>
            </li>
            <li class="page-item">
                <span class="page-link text-muted">&laquo; prev</span>
            </li>
            {% endif %}

            <li class="page-item">
                <span class="page-link text-dark">
                    {{verses.number}} / {{verses.paginator.num_pages}}
                </span>
            </li>

            {% if verses.has_next %}
            <li class="page-item">
                <a class="page-link text-dark" href="{% url 'book' %}?name={{book}}&page={{verses.next_page_number}}">
                    next &raquo;
                </a>
            </li>
            <li class="page-item">
                <a class="page-link text-dark" href="{% url 'book' %}?name={{book}}&page={{verses.paginator.num_pages}}">
                    last &raquo;
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <span class="page-link text-muted">next &raquo;</span>
            </li>
            <li class="page-item">
                <span class="page-link text-muted">last &raquo;</span>
            </li>
            {% endif %}
        </ul>
        {% csrf_token %}
        <form action="?name={{book}}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="go" class="btn btn-primary btn-dark">
    </body>
{% endblock %}

Church/forum/templates/forum/forum.html
{% extends "base.html" %}

{% block main %}
    <body>
       
        <h1>{{name}} {{chapter.chapter_number}}-{{verse.verse_number}}
        <h3>{{verse.text}}</h3>
        {% if can_post == 1 %}
        {% csrf_token %}
        <form action="?name={{name}}&chapter={{chapter.chapter_number}}&verse={{verse.verse_number}}" method="post">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="post" class="btn btn-primary btn-dark">
        {% else %}
        <p class="text-dark">Posting frequency exceeds the limit.</p>
        {% endif %}
        
        {% if verse.image %}
        <h2>Keyword Visualization</h2>
            <img src="/media/img/wordcloud/{{ name }}_{{ chapter.chapter_number }}_{{ verse.verse_number }}.png" class="img-fluid">

        {% else %}

        {% endif %}
        
        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">Post id</th>
                <th scope="col">Name</th>
                <th scope="col">User id</th>
                <th scope="col">Date</th>
                <th scope="col">Content</th>
            </tr>
                {% for p in post %}
                <tr>
                    <td>{{ p.id }}</td>
                    {% if p.owner is not None %}
                    <td>
                        <a class="page-link text-dark" href="{% url 'userpage:userpage' p.owner.username %}">
                            {{ p.owner.username }}
                        </a>
                    </td>
                    {% else %}
                    <td>{{ p.guest_name }}</td>
                    {% endif %}
                    {% if p.owner is not None %}
                    <td>{{user.id}}</td>
                    {% else %}
                    <td>guest</td>
                    {% endif %}
                    <td>{{p.created_at}}</td>
                    <td>{{p.text}}</td>
                </tr>
                {% endfor %}
        </table>
    </body>
{% endblock %}

Church/forum/templates/forum/list.html
{% extends "base.html" %}

{% block main %}
    <body>
       
        {% for book in books %}
        <a class="page-link text-dark" href="{% url 'book' %}?name={{ book.name }}"><p>{{book.name}}</p></a>
        {% endfor %}
    </body>
{% endblock %}