Church/Church/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('menu/',include('menu.urls')),
    path("accounts/", include("accounts.urls")),
    path("store/",include("store.urls")),
    path("userpage/",include("userpage.urls")),
    path("mypage/",include("mypage.urls")),
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #後で理解

Church/menu/urls.py
from django.urls import path,include
from . import views


urlpatterns = [
    path('',views.index,name='index'),
    path('list/',include('forum.urls')),
    path('dogmatics/',include('dogmatics.urls')),
    path('back/',views.back,name="back"),
]

Church/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('checkout',views.checkout,name='checkout'),
    path('success',views.success,name='success'),
    path('cancel',views.cancel,name='cancel'),
    path('create-checkout-session',views.create_checkout_session,name='cancel'),
    path('webhook', views.handle_webhook, name='webhook'),
    path('product_list', views.product_list, name='product_list'),
]

Church/store/forms.py
from django import forms 

class DiscussionForm(forms.Form):
    
    quantity = forms.IntegerField(required=True, min_value=1)
    

Church/store/views.py
import stripe
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings


stripe.api_key = 'sk_test_51QM2PUBqD5txSTx2CKj3jmDHr2mA8OwXjvc0FeyGOdjPiyTWIt8RdrE6iKznM21nQ7GxBNxVRWNoAtMtzyBIB2Qt00bVFRLu3B'


def checkout(request):
    return render(request, "store/checkout.html")


def success(request):
    return render(request, "store/success.html")


def cancel(request):
    return render(request, "store/cancel.html")

def product_list(request):

    products = stripe.Product.list()

    if not products:
        print("!エラー!")

    products_list =[]

    for product in products:


        if product['active']:
            
            name = product['name']
            image = product['images']

            prices = stripe.Price.list(product=product['id'])

            price_list = []
            num = len(prices)

            for p_price in prices:

                nickname = p_price['nickname']
                price = str(p_price['unit_amount'])
                currency = p_price['currency']
                id = p_price['id']
               
                type_list = {

                            'price':price, 
                            'nickname':nickname,
                            'currency':currency,
                            'id':id,
                           
                             }
            
                price_list.append(type_list)

            product_list = {

                'name' : name,
                'image' : image,
                'price_list' : price_list, 
                'num' : num,

            }

        else:
            print(product["name"]+" is False.")

        products_list.append(product_list)

    params = {
        'products_list' : products_list
    }
    print(params)



    return render(request, "store/product_list.html", params)


@csrf_exempt
def create_checkout_session(request):

    if (request.method == 'POST'):
         
        price = request.POST["price"]
    
    checkout_session = stripe.checkout.Session.create(
            line_items=[{
                'price':price,
                'quantity':1
            },],
            mode='payment',
            success_url=
            'http://127.0.0.1:8000/store/success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url= 'http://127.0.0.1:8000//store/cancel',)
    
    return render(request, 'store/checkout.html', {'checkout_url': checkout_session.url})

        # ここもう少しハンドリングするべき


endpoint_secret = 'whsec_7dfaa602ece8bbc9c1c974c457ddce66b205bcdfbb691b5422cefc4ec65f79c2'


@csrf_exempt
def handle_webhook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        # Stripeが送ってきたものか判定
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
    except ValueError:
        # Payloadが変な時
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError:
        # Stripeでない第三者が不正に送ってきた時
        return HttpResponse(status=400)

    # eventのtypeによって、好きなように分岐
    if event['type'] == 'payment_intent.succeeded':
        payment_intent = event['data']['object']
        metadata = payment_intent["metadata"]
        print('決済が完了したのでここで決済処理をします！！！')
        print("決済の詳細情報→" + str(payment_intent))
        print("指定したメタデータの取り出し→" + str(metadata))

    else:
        event_type = event['type']
        print(f'Event type {event_type}')
    return HttpResponse(status=200)

Church/store/templates/store/cancel.html
{% extends "base.html" %}
{% block main %}
<body>
  <section>
    <p>The payment was cancelled</p>
    <p><a href="{% url 'store:product_list' %}">back</a></p>
  </section>
</body>
{% endblock %}

Church/store/templates/store/checkout.html
<!DOCTYPE html>
<html>
<head>
    <title>Redirecting to Stripe...</title>
    <script>
        // ページ読み込み時にリダイレクト
        document.addEventListener('DOMContentLoaded', function() {
            window.location.href = "{{ checkout_url }}";  // Djangoから渡されたCheckout URL
        });
    </script>
</head>
<body>
    <p>Redirecting to Stripe checkout...</p>
</body>
</html>

Church/store/templates/store/product_list.html
{% extends "base.html" %}

{% block main %}
<div class="container my-5">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for product in products_list %}
        <div class="col">
            <div class="card h-100 shadow-sm">
                <!-- 商品画像 -->
                {% if product.image %}
                    <div class="text-center">
                        {% for image in product.image %}
                            <img src="{{ image }}" class="card-img-top img-fluid" alt="{{ product.name }}">
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="card-body">
                        <p class="text-center text-muted">No image available!</p>
                    </div>
                {% endif %}

                <!-- 商品情報 -->
                <div class="card-body">
                    <h5 class="card-title text-dark text-center">{{ product.name }}</h5>

                    {% if product.num != 1 %}
                        {% for price in product.price_list %}
                            <p class="card-text text-center">
                                <strong>{{ price.nickname }} {{ price.price }} {{ price.currency }} </strong>
                            </p>
                            <form action="/store/create-checkout-session" method="POST" class="text-center">
                                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                                <input type="hidden" name="price" value="{{ price.id }}">
                                <button type="submit" class="btn btn-primary btn-sm btn-dark">Checkout</button>
                            </form>
                        {% endfor %}
                    {% else %}
                        {% for price in product.price_list %}
                            <p class="card-text text-center">
                                <strong>{{ price.price }} {{ price.currency }}</strong>
                            </p>
                            <form action="/store/create-checkout-session" method="POST" class="text-center">
                                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                                <input type="hidden" name="price" value="{{ price.id }}">
                                <button type="submit" class="btn btn-primary btn-sm btn-dark">Checkout</button>
                            </form>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Church/store/templates/store/success.html
{% extends "base.html" %}
{% block main %}
<body>
  <section>
    <p>Payment completed</p>
    <p><a href="{% url 'store:product_list' %}">back</a></p>
  </section>
</body>
{% endblock %}